PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ns1:     <http://www.theworldavatar.com/ontology/ontocape/upper_level/system.owl#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX gasgrid: <http://www.theworldavatar.com/ontology/ontogasgrid/gas_network_system.owl#>
PREFIX loc:     <http://www.bigdata.com/rdf/geospatial/literals/v1#>
PREFIX geo:     <http://www.bigdata.com/rdf/geospatial#>
PREFIX comp:	<http://www.theworldavatar.com/ontology/ontogasgrid/gas_network_components.owl#>

SELECT (COUNT(*) AS ?RESULT)
WHERE
{
	?pipe rdf:type gasgrid:GridPipeline.
	?pipe rdfs:label ?label.
	?pipe ns1:hasSubsystem ?segment.
	?segment gasgrid:hasEndPart ?end.
	?end gasgrid:entersPipeConnection ?connection.
	?connection loc:lat-lon ?location.
	?connection gasgrid:hasOrder ?order.
}