version: "3.8"

# Services
services:

  # FTP Server
  vsftpd:
    build:
      context: vsftpd
    container_name: "vsftpd-${MODE}"
    image: docker.cmclinnovations.com/vsftpd:1.0.0-SNAPSHOT
    environment:
      PASV_ADDRESS: 77.95.36.39
    env_file:
      - vsftpd/vsftpd_credentials.env
    labels:
      authors: "support@cmclinnovations"
      builder: "${BUILDER}"
      description: "Simple FTP server."
      hash: "${HASH}"
    restart: unless-stopped
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
      
  # Blazegraph
  blazegraph:
    ports:
      - "8889:8080"

  # Blazegraph geo
  blazegraph_geo:
    ports:
      - "8989:8080"

  # Postgres
  postgres:
    ports:
      - "7432:5432"

  # RDF4J
  rdf4j:
    ports:
      - "8888:8080"


# Development network
networks:
  default:
    name: dev-db