# Name workflow
name: Python Testing Workflow

# Read only permissions
permissions: read-all

# Triggered at 02:00 daily
on:
  schedule:
    - cron: '0 2 * * *'

# Listing of jobs to be run
jobs:

  # Checks the availability of KG endpoints
  availabilty-tests:
    name: Endpoint Availability Tests
    runs-on: ubuntu-latest
    
    # Use the environment configured with secrets
    environment: python-test-environment
    
    # Set the working directory?
    defaults:
      run:
        working-directory: tests
       
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
        ref: 'dev-tests'
      
      # Configure python
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      # Output the python version
      - name: Display version
        run: python -c "import sys; print(sys.version)"
  